
name: Backend-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./server-jvm
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
  
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: ./gradlew build -x test
      
      - name: Run tests
        working-directory: ${{ env.working-directory }}
        run: ./gradlew test
