
name: Frontend-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
        
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:unit
