
name: Frontend-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    env:
      working-directory: ./client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install
        
      - name: Run tests
        working-directory: ${{ env.working-directory }}
        run: yarn test:unit
        
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    env:
      client-directory: ./client
      server-directory: ./server-js
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Install dependencies(client)
        working-directory: ${{ env.client-directory }}
        run: yarn install
      
      - name: Install dependencies(server)
        working-directory: ${{ env.server-directory }}
        run: npm install
      
      - name: Run server
        working-directory: ${{ env.server-directory }}
        run: node app.js
      
      - name: Run client
        working-directory: ${{ env.client-directory }}
        run: yarn serve
      
      - name: Run tests
        working-directory: ${{ env.client-directory }}
        run: yarn test:e2e
